[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
# remappings = ['contracts/:@openzeppelin/=node_modules/@openzeppelin/']
solc = "0.8.22"
optimizer = true
via_ir = false

# add via_ir profile
additional_compiler_profiles = [ { name = "via-ir", via_ir = true } ]

# enforce compiling tests without via_ir and only some heavy contract with via_ir
# note: it will only work if tests are using vm.deployCode to deploy contract
compilation_restrictions = [
    { paths = "contracts/fun/Bonding.sol", via_ir = true },
    { paths = "contracts/genesis/Genesis.sol", via_ir = true },
    { paths = "contracts/tax/AgentTax.sol", via_ir = true },
    { paths = "contracts/virtualPersona/AgentFactoryV3.sol",via_ir = true },
    { paths = "contracts/virtualPersona/AgentFactory.sol",via_ir = true }
]
